.TH MAN 1 2014-04-26 "Linux" "skroll"
.SH NAME
skroll - make a given text scroll
.SH SYNOPSIS
.B skroll
.RI [\| \-hl\| ]\ [\| -n\ num\| ]\ [\| -d\ delay\| ]
.SH DESCRIPTION
.PP
.B skroll
reads text on stdin and make it scroll to stdout
.TP
.B \-h
Display a help text
.B \-l
Loop text forever
.B \-n num
Show <num> char at a time
.B \-d delay
Make scroll steps last <delay> seconds
.SH BUGS
.PP
No bugs known actually. Feel free to report them at willy@mailoo.org
.SH AUTHORS / CONTRIBUTORS
Willy Goiffon is the main author.
